bengaltraining/bengaltraining/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    url(r'^accounts/',include('accounts.urls')),
    url(r'^poll/',include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$',include('polls.urls')),
]
urlpatterns += staticfiles_urlpatterns()

bengaltraining/polls/urls.py
from django.conf.urls import url
from . import views
app_name='polls'
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^profile$',views.profile,name='profile'),
    url(r'^admin$',views.admin,name='admin'),
    url(r'^createpolls$',views.createpolls,name='createpoll'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<question_id>[0-9]+)/getdata/$', views.getdata, name='getdata'),
]

bengaltraining/polls/models.py
from django.db import models
from django.contrib.auth.models import User
from profileinfo.models import interest

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User,default=None)
    tag=models.ForeignKey(interest,default=None,blank=False)
    total = models.IntegerField(default=0)
    music = models.IntegerField(default=0)
    painting = models.IntegerField(default=0)
    poetry = models.IntegerField(default=0)
    technology = models.IntegerField(default=0)
    vote = models.IntegerField(default=0)
    
    

    def __str__(self):
        return self.question_text
        

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class VoteViewCounter(models.Model):
    Question=models.OneToOneField(Question, on_delete=models.CASCADE)
    votedUser=models.ManyToManyField(User,related_name = 'votedUser')
    viewedUser=models.ManyToManyField(User, related_name = 'viewedUser')
    
    
    

bengaltraining/polls/forms.py
from django import forms
from . import models

class createpoll(forms.ModelForm):
    class Meta:
        model=models.Question
        fields=['question_text','tag']
  
    def clean_question_text(self):
        data = self.cleaned_data['question_text']  
        if "?" not in data:
            raise forms.ValidationError("Not a question")
        return data


class takechoice(forms.ModelForm):
    class Meta:
        model=models.Choice
        fields=['choice_text']
    def getit(self):
        return models.Choice.choice_text

bengaltraining/polls/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponseRedirect, HttpResponse,JsonResponse
from django.urls import reverse
from .models import Question,Choice,VoteViewCounter
from profileinfo.models import info
from django.contrib.auth.decorators import login_required
from . import forms
from django.core.paginator import Paginator

def index(request):
  
    latest_question_list = Question.objects.order_by('-pub_date')
    message = request.session.get('message')
    paginator=Paginator(latest_question_list,3)
    page=request.GET.get('page')
    if request.GET.get('page'):
        latest_question_list=paginator.page(page)
    else:
        latest_question_list=paginator.page(1)  
    context = {'latest_question_list': latest_question_list}
    if message!="no message":
        context = {'latest_question_list': latest_question_list,'message':message}
        request.session['message'] = "no message"
    return render(request, 'polls/index.html', context)


def profile(request):
    
    latest_question_list = Question.objects.order_by('-pub_date').filter(user=request.user)
    paginator=Paginator(latest_question_list,10)
    page=request.GET.get('page')
    if request.GET.get('page'):
        latest_question_list=paginator.page(page)
    else:
        latest_question_list=paginator.page(1)  
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/profile.html', context)


def admin(request):
    
    latest_question_list = Question.objects.order_by('-pub_date')
    paginator=Paginator(latest_question_list,10)
    page=request.GET.get('page')
    if request.GET.get('page'):
        latest_question_list=paginator.page(page)
    else:
        latest_question_list=paginator.page(1)  
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/admin.html', context)


@login_required(login_url="/accounts/signin/")    
def detail(request, question_id):
    
    question = get_object_or_404(Question, pk=question_id)
    user=question.user
    counter=VoteViewCounter.objects.get(Question=question)
    voters=counter.votedUser.all()
    viewers=counter.viewedUser.all()
    if request.user in voters:
        voterStatus="voter"
    else:
        voterStatus="non voter"
    if request.is_ajax():
        if request.user in viewers:
            #counting the interest clicks for each question
            print("here")
        else:
            profile=info.objects.all().filter(user=request.user)
            profile=profile[0]
            interests=profile.interest.all()
            if request.user!= question.user:
                question.total+=1
                # loop interests queryset to increment view counter
                for interest in interests:
                    selected=interest.title
                    print(selected)
                    if(selected=='music'):
                        question.music+=1
                    if(selected=='painting'):
                        question.painting+=1
                    if(selected=='peotry'):
                        question.poetry+=1
                    # common question save for every category
                question.save()
                counter.viewedUser.add(request.user)
                counter.save()
    
    
    return render(request, 'polls/details.html', {'question': question,'user':user,'voterstatus':voterStatus})

def getdata(request, question_id):
    
    question = get_object_or_404(Question, pk=question_id)
    choices=question.choice_set.all()
    listchoice=[]
    datas=[]
    # print(choices.count())
    for i in range(choices.count()):
        listchoice.append(choices[i].choice_text)
        datas.append(choices[i].votes)

    data={
        "choice":listchoice,
        "datas":datas
    }
    return JsonResponse(data)


#showing the result for super-user 
def results(request, question_id):
    
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/result.html', {'question': question})


def vote(request, question_id):
    
    question = get_object_or_404(Question, pk=question_id)
    question.vote+=1
    question.save()
    print(question.user)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/details.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        counter=VoteViewCounter.objects.get(Question=question)
        counter.votedUser.add(request.user)
        counter.save()
        latest_question_list = Question.objects.order_by('-pub_date')
        paginator=Paginator(latest_question_list,3)
        latest_question_list=paginator.page(1)
        message='Thank you for your vote. Please check out other questions'
        request.session['message'] = message
        return redirect("polls:index")


@login_required(login_url="/accounts/signin/")
def createpolls(request):
   
    if request.method=="POST":
        form=forms.createpoll(request.POST)
        choices=forms.takechoice(request.POST)
        #print(request.POST)
        try:
            if form.is_valid and choices.is_valid:
                temp=form.save(commit=False)
                temp.user=request.user
                temp.save()          
                qus=Question.objects.get(question_text=temp.question_text)
                counter=VoteViewCounter(Question=qus)
                counter.save()
                counter.votedUser.add(request.user)
                counter.save()
                counter.viewedUser.add(request.user)
                counter.save()
                x=request.POST.getlist('choice_text')
                #creating 3 choices
                for i in range(len(x)):
                    instance=Choice(question=qus,choice_text=x[i])
                    instance.save()
                #choices.save()
                message='Thank you for creating new question.Please check out other questions'
                request.session['message'] = message
                return redirect('polls:index')
        except:
            error="Your question was not valid!!"
            form=forms.createpoll()
            choices=forms.takechoice()
            return render(request,"polls/createpolls.html",{'form':form,'choice':choices,"error":error})
    else:
        form=forms.createpoll()
        choices=forms.takechoice()
    return render(request,"polls/createpolls.html",{'form':form,'choice':choices})

bengaltraining/polls/templates/polls/admin.html
{% extends 'base_layout.html' %}
{% block content %}
{% if user.is_superuser %}
{% if latest_question_list %}
    <br>
    <br>
    <h1 style="text-align:center">Admin Panel</h1>
    <br>
    {% if message %}
    <div class="alert alert-success" >
            {{message}}
    </div>
    {% endif %}
  
    <div class="container">
            <table class="table table-hover">
            <thead>
                <tr>
                <th>Title</th>
                <th>Publication Date</th>
                <th>User</th>
                <th>Tag</th>
                <th>Total View</th>
                <th>Total Vote</th>
                <th>Music Viewer</th>
                <th>Technology</th>
                <th>Poetry</th>
                <th>Painting</th>
                
                </tr>
            </thead>
    {% for question in latest_question_list %}
            <tbody>
                <tr>
                <td> <a href="{% url 'polls:detail' question.id %}" style="text-decoration:none">{{question.question_text}}</a></td>
                <td>{{question.pub_date}}</td>
                <td>{{question.user}}</td>
                <td>{{question.tag}}</td>
                <td>{{question.total}}</td>
                <td>{{question.vote}}</td>
                <td>{{question.music}}</td>
                <td>{{question.technology}}</td>
                <td>{{question.poetry}}</td>
                <td>{{question.painting}}</td>
                </tr>
            </tbody>    
    {% endfor %}
    </table>
    </div>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<div class="pagination">
    <span class="step-links">
        {% if latest_question_list.has_previous %}
            <a class="btn btn-primary" href="?page=1"> First</a>
            <a class="btn btn-primary" href="?page={{ latest_question_list.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ latest_question_list.number }} of {{ latest_question_list.paginator.num_pages }}
        </span>

        {% if latest_question_list.has_next %}
            <a class="btn btn-primary" href="?page={{ latest_question_list.next_page_number }}">Next</a>
            <a class="btn btn-primary" href="?page={{ latest_question_list.paginator.num_pages }}">Last</a>
        {% endif %}
    </span>
</div>
{% else %}
<div class="alert alert-danger" >
    User is not Admin!!
</div>
{% endif %}
{% endblock %}

bengaltraining/polls/templates/polls/createpolls.html
{% extends 'base_layout.html' %}
{% block content %}
{% if error %}
<div class="alert alert-danger" >
        {{error}}
</div>
{% endif %}
<br>
<h2>Create new article</h2>
<form action="{% url 'polls:createpoll' %}" method="POST" id="question">
{% csrf_token %}
{{form}}
{{choice}}
{{choice}}
{{choice}}
<br>
<input type="submit" value="Submit Poll"class="btn btn-primary">
</form>
{% endblock %}

bengaltraining/polls/templates/polls/details.html
{% extends 'base_layout.html' %}
{% block content %}
<br><br>
<h1>{{ question.question_text }}</h1>
{% if error_message %}
<div class="alert alert-danger ">
{{ error_message }}
</div>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<br>
{% for choice in question.choice_set.all %}

<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />

{% endfor %}
<br>
<br>

{% if question.user != request.user %}
{% if voterstatus == "voter" %}
<input type="submit" value="Already Voted" class="btn btn-secondary" disabled/>
{% else %}
<input type="submit" value="Vote" class="btn btn-primary"/>
{% endif %}
{% endif %}
</form>
{% if request.user.is_superuser or user == request.user %}

<br>
<br>
<h3>Result</h3>
<table class="table table-hover">
    <thead>
        <tr>
        <th>Cetagory</th>
        <th>Number of Votes</th>
        </tr>
    </thead>
    <tbody></tbody>
        {% for choice in question.choice_set.all %}    
          <tr>
            <td>{{ choice.choice_text }}</td>
            <td>{{ choice.votes }} vote{{ choice.votes|pluralize }}</td>
          </tr>                
        {% endfor %}
</tbody>
</table>
<section>
<canvas id="myChart" width="100" height="100"></canvas>
</section>
{% endif %}

{% endblock %}

bengaltraining/polls/templates/polls/index.html
{% extends 'base_layout.html' %}
{% block content %}
{% if latest_question_list %}
    
    <br>
    
    <h1 class="title">Latest Questions Now</h1>
    <br>
    {% if message %}
    <div class="alert alert-success" >
            {{message}}
    </div>
    {% endif %}
    <ul>
    {% for question in latest_question_list %}
    <a onclick="count('{{question.id}}');" href="{% url 'polls:detail' question.id %}" style="text-decoration:none">
    <div class="card ">
            <div class="card-body">{{ question.question_text }}</div>
            <div class="card-footer ">Auther: {{ question.user|title }}
                <br>
                Tag: {{ question.tag|title }}
            </div>
          </div>
        </a> 
        <br>    
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<div class="pagination">
    <span class="step-links">
        {% if latest_question_list.has_previous and latest_question_list.has_next  %}
            <a class="btn btn-primary" href="?page=1"> First</a>
            <a class="btn btn-primary" href="?page={{ latest_question_list.previous_page_number }}">Previous</a>
            <span class="current">
                Page {{ latest_question_list.number }} of {{ latest_question_list.paginator.num_pages }}
            </span>
            <a class="btn btn-primary" href="?page={{ latest_question_list.next_page_number }}">Next</a>
            <a class="btn btn-primary" href="?page={{ latest_question_list.paginator.num_pages }}">Last</a>        
        {% elif latest_question_list.has_previous %}
            <a class="btn btn-primary" href="?page=1"> First</a>
            <a class="btn btn-primary" href="?page={{ latest_question_list.previous_page_number }}">Previous</a>
            <span class="current">
                Page {{ latest_question_list.number }} of {{ latest_question_list.paginator.num_pages }}
            </span>
            <a class="btn btn-secondary"  href="#">Next</a>
            <a class="btn btn-secondary"  href="#">Last</a>      

        {% elif latest_question_list.has_next %}
            <a class="btn btn-secondary"  href="#">First</a>
            <a class="btn btn-secondary"  href="#">Previous</a>
            <span class="current">
                Page {{ latest_question_list.number }} of {{ latest_question_list.paginator.num_pages }}
            </span>
            <a class="btn btn-primary" href="?page={{ latest_question_list.next_page_number }}">Next</a>
             <a class="btn btn-primary" href="?page={{ latest_question_list.paginator.num_pages }}">Last</a>     
        {% endif %}
    </span>
</div>


{% endblock %}

bengaltraining/polls/templates/polls/profile.html
{% extends 'base_layout.html' %}
{% block content %}
{% if latest_question_list %}
    
       <br>
    <h1 class="title">{{request.user.username|title}}'s Questions </h1>
    <br>
    {% if message %}
    <div class="alert alert-success" >
            {{message}}
    </div>
    {% endif %}
  
    <div class="container">
            <table class="table table-hover">
            <thead>
                <tr>
                <th>Title</th>
                <th>Publication Date</th>
                <th>Tag</th>
                <th>Total View</th>
                <th>Total Vote</th>
                </tr>
            </thead>
    {% for question in latest_question_list %}
            <tbody>
                <tr>
                <td> <a href="{% url 'polls:detail' question.id %}" style="text-decoration:none">{{question.question_text}}</a></td>
                <td>{{question.pub_date}}</td>
                <td>{{question.tag}}</td>
                <td>{{question.total}}</td>
                <td>{{question.vote}}</td>
                </tr>
            </tbody>    
    {% endfor %}
    </table>
    </div>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<div class="pagination">
    <span class="step-links">
        {% if latest_question_list.has_previous %}
            <a class="btn btn-primary" href="?page=1"> First</a>
            <a class="btn btn-primary" href="?page={{ latest_question_list.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ latest_question_list.number }} of {{ latest_question_list.paginator.num_pages }}
        </span>

        {% if latest_question_list.has_next %}
            <a class="btn btn-primary" href="?page={{ latest_question_list.next_page_number }}">Next</a>
            <a class="btn btn-primary" href="?page={{ latest_question_list.paginator.num_pages }}">Last</a>
        {% endif %}
    </span>
</div>


{% endblock %}

bengaltraining/polls/templates/polls/result.html
{% extends 'base_layout.html' %}
{% block content %}
{% if user.is_superuser %}
<h1>{{ question.question_text }}</h1>
<br>
<br>
<ul>

</ul>
{% else %}
<br>
<br>
<div class="alert alert-danger" >
     You are not authorized to see result
</div>
{% endif %}

{% endblock %}