bengaltraining/accounts/urls.py
from django.conf.urls import url
from . import views

app_name='accounts'

urlpatterns=[

    url(r'^signup/$',views.signup_view,name="signup"),
    url(r'^signin/$',views.signin_view,name="signin"),
    url(r'^logout/$',views.logout_view,name="logout"),
    url(r'^personal/$',views.personal_view,name="personal"),
]

bengaltraining/bengaltraining/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    url(r'^accounts/',include('accounts.urls')),
    url(r'^poll/',include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$',include('polls.urls')),
]
urlpatterns += staticfiles_urlpatterns()

bengaltraining/polls/urls.py
from django.conf.urls import url
from . import views
app_name='polls'
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^profile$',views.profile,name='profile'),
    url(r'^admin$',views.admin,name='admin'),
    url(r'^createpolls$',views.createpolls,name='createpoll'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<question_id>[0-9]+)/getdata/$', views.getdata, name='getdata'),
]

bengaltraining/templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="csrf-token" content="{{csrf_token}}">
        <title>Bengal Training</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
    </head>
    <body>
        <header class="wrapper">
           
            <nav class="navbar navbar-expand-sm bg-primary navbar-dark mr-auto">
                <a class="navbar-brand" href="{% url 'polls:index' %}">Bengal-Training</a>
                      <!-- Links -->
                      <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:profile' %}">My Questions</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:createpoll' %}">New Question</a>
                        </li> 
                        {% if request.user.is_superuser %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:admin' %}">Admin panel</a>
                        </li> 
                        {% endif %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'accounts:signin' %}">Login</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link " href="{% url 'accounts:signup' %}">Signup</a>
                        </li>
                        {% endif %}
                      </ul>
                    
                    </nav>
        </header>
        <div class="wrapper-body">
            <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        </div>
    </body>
</html>

<script>
    // for styling only
    var elem = document.getElementById("id_interest");
     elem.classList.add('form-control');
</script>
<script>
//for counting user seen
function count(id) {    
    $.ajax({
            type: "GET",
            url: '/poll/'+id,
            data: {
            }
        })
        .done(function( msg ) {
           
        });
}
$( document ).ready(function() {

    console.log(window.location.href);
    url=window.location.href;
    id=url.slice(27,29);
    var choice=[];
    var datas=[2,3,4];
    $.ajax({
            type: "GET",
            url: '/poll/'+id+'/getdata',
            success:function(data){
                console.log(data.datas);
                choice=data.choice
                datas=data.datas
                var ctx = document.getElementById('myChart').getContext('2d');
                var myChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: choice,
                    datasets: [{
                        label: '# of Votes',
                        data: datas,
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(60, 217, 86, 0.2)',
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(60, 217, 86, 1)',
                        ],
                        borderWidth: 2
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
            },
            error:function(error){
                console.log(error);
            }
        });
        
});

</script>
<script>
 
  $(document).ready(function(){
        $("#vote").click(function(){
        $(".alert").show("fade");
        
    });
    $(".close").click(function(){
        window.location.replace("/");  
    });
  }); 
 
</script>